pipeline {
    agent{
        node {
            label 'Agent-1'
        }
    }

    options {
        disableConcurrentBuilds()
        ansicolor('xterm')
    }

    parameters {
        choice(name: 'CHOICE', choices: ['apply', 'destroy'], description: 'Pick something')
    }

    stages {
        stage('Init') {
            steps {
                sh """
                cd 00-VPC
               terraform init -reconfigure
                """
            }
        }
        stage('plan') {
            steps {
                sh """
                cd 00-VPC
                terraform plan
                """
            }
        }
        stage('Deploy') {
            when {
                expressions {
                    expression { params.CHOICE == 'apply' || params.CHOICE == 'destroy'
                }
            
            
            }
            
            steps {
                sh """
                cd 00-VPC
                terraform $params.CHOICE -auto-approve
                """
            }

        }
    }
}